//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialApp.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string Text { get; set; }
        public Nullable<int> PostID { get; set; }
        public Nullable<int> CommentBy { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
